nginx:
    build: ./nginx
    links:
        - node0:node0
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node0:
    build: ./node-master
    links:
        - redis
node1:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node2:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
node3:
    build: ./node
    links:
        - redis
    ports:
        - "8080"
redis:
    image: redis:2.8.23
    ports:
        - "6379"